### ISSUE TITLE
IE 11에서 메뉴 버튼들 클릭해도 페이지 이동되지 않음

### ISSUE THREAD

**Issue by realstone** [LaunchArea/saladgram#5]
MENU, OUR STORY, STORE, 로그인, 로그아웃, 회원가입등 눌러도 페이지 이동안됨
![image](https://cloud.githubusercontent.com/assets/8033292/16067423/6cc78778-32f7-11e6-9f38-030c508b3e37.png)

**Comment by JackYoon** [comment]
윈도우8.1 IE 11 에서도 동일증상
